# Generated by Django 6.0.2 on 2026-02-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGING_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('content', models.TextField()),
                ('document', models.FileField(upload_to='documents/')),
                ('date', models.DateField()),
                ('blog_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOGING_APP.blogger')),
            ],
        ),
    ]
